name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Learning Lab User"
          secondGreeting: "Ooooooh qué pasó, me neño!"
          thirdGreeting: "Just the fuck up, dude!"
